update_flake8

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -38,7 +38,17 @@ jobs:
       - name: Install project
         run: poetry install --no-interaction
       
-      - name: Check code style
+      - name: Install flake8
+        run: poetry run python -m pip install flake8
+      
+      - name: Run flake8 - Critical Errors
         run: |
-          poetry run python -m pip install flake8
           poetry run flake8 azdo_harvest/ --count --select=E9,F63,F7,F82 --show-source --statistics
+      
+      - name: Run flake8 - Full Check
+        run: |
+          poetry run flake8 azdo_harvest/ --count --max-line-length=100 --show-source --statistics
+          if [ $? -ne 0 ]; then
+            echo "flake8 found errors!"
+            exit 1
+          fi
